shiny:
  proxy:
    title: Carson Sievert's Shiny Applications
    logo-url: https://cpsievert.me/favicon.ico
    landing-page: /
    heartbeat-rate: 10000
    heartbeat-timeout: 60000
    port: 8080
    authentication: none
    # Note that this configuration shouldn't be used in enterprise/production
    # environments -- https://www.shinyproxy.io/configuration/#docker
    docker:
      cert-path: /home/none
      url: http://localhost:2375
      port-range-start: 20000
  apps:
  - name: 3Dnormal
    display-name: 3Dnormal
    description: Linked brushing in a grand tour of 3-dimensional data.
    docker-cmd: ["R", "-e", "shiny::runApp()"]
    docker-image: cpsievert/apps:shiny-3Dnormal
  - name: bcviz
    display-name: bcviz
    description: ...
    docker-cmd: ["R", "-e", "shiny::runApp()"]
    docker-image: cpsievert/apps:shiny-bcviz
  - name: brush2plotly
    display-name: brush2plotly
    description: ...
    docker-cmd: ["R", "-e", "shiny::runApp()"]
    docker-image: cpsievert/apps:shiny-brush2plotly
  - name: cdf
    display-name: cdf
    description: ...
    docker-cmd: ["R", "-e", "shiny::runApp()"]
    docker-image: cpsievert/apps:shiny-cdf
  - name: clearBrush
    display-name: clearBrush
    description: ...
    docker-cmd: ["R", "-e", "shiny::runApp()"]
    docker-image: cpsievert/apps:shiny-clearBrush
  - name: CLT
    display-name: CLT
    description: ...
    docker-cmd: ["R", "-e", "shiny::runApp()"]
    docker-image: cpsievert/apps:shiny-CLT
  - name: eechidna
    display-name: eechidna
    description: ...
    docker-cmd: ["R", "-e", "shiny::runApp()"]
    docker-image: cpsievert/apps:shiny-eechidna
  - name: ggtree
    display-name: ggtree
    description: ...
    docker-cmd: ["R", "-e", "shiny::runApp()"]
    docker-image: cpsievert/apps:shiny-ggtree
  - name: intervals
    display-name: intervals
    description: ...
    docker-cmd: ["R", "-e", "shiny::runApp()"]
    docker-image: cpsievert/apps:shiny-intervals
  - name: LDAelife
    display-name: LDAelife
    description: ...
    docker-cmd: ["R", "-e", "shiny::runApp()"]
    docker-image: cpsievert/apps:shiny-LDAelife
  - name: lmGadget
    display-name: lmGadget
    description: ...
    docker-cmd: ["R", "-e", "shiny::runApp()"]
    docker-image: cpsievert/apps:shiny-lmGadget
  - name: pitchRx
    display-name: pitchRx
    description: ...
    docker-cmd: ["R", "-e", "shiny::runApp()"]
    docker-image: cpsievert/apps:shiny-pitchRx
  - name: pitchRx-db
    display-name: pitchRx-db
    description: ...
    docker-cmd: ["R", "-e", "shiny::runApp()"]
    docker-image: cpsievert/apps:shiny-pitchRx-db
  - name: pitchRx2
    display-name: pitchRx2
    description: ...
    docker-cmd: ["R", "-e", "shiny::runApp()"]
    docker-image: cpsievert/apps:shiny-pitchRx2
  - name: plotlyAg
    display-name: plotlyAg
    description: ...
    docker-cmd: ["R", "-e", "shiny::runApp()"]
    docker-image: cpsievert/apps:shiny-plotlyAg
  - name: plotlyEvents
    display-name: plotlyEvents
    description: ...
    docker-cmd: ["R", "-e", "shiny::runApp()"]
    docker-image: cpsievert/apps:shiny-plotlyEvents
  - name: plotlyLinkedBrush
    display-name: plotlyLinkedBrush
    description: ...
    docker-cmd: ["R", "-e", "shiny::runApp()"]
    docker-image: cpsievert/apps:shiny-plotlyLinkedBrush
  - name: plotlyLinkedClick
    display-name: plotlyLinkedClick
    description: ...
    docker-cmd: ["R", "-e", "shiny::runApp()"]
    docker-image: cpsievert/apps:shiny-plotlyLinkedClick
  - name: plotlyViewer
    display-name: plotlyViewer
    description: ...
    docker-cmd: ["R", "-e", "shiny::runApp()"]
    docker-image: cpsievert/apps:shiny-plotlyViewer
  - name: regInf
    display-name: regInf
    description: ...
    docker-cmd: ["R", "-e", "shiny::runApp()"]
    docker-image: cpsievert/apps:shiny-regInf
  - name: sampling
    display-name: sampling
    description: ...
    docker-cmd: ["R", "-e", "shiny::runApp()"]
    docker-image: cpsievert/apps:shiny-sampling
  - name: testing
    display-name: testing
    description: ...
    docker-cmd: ["R", "-e", "shiny::runApp()"]
    docker-image: cpsievert/apps:shiny-testing
  - name: testing2
    display-name: testing2
    description: ...
    docker-cmd: ["R", "-e", "shiny::runApp()"]
    docker-image: cpsievert/apps:shiny-testing2
  - name: topnames
    display-name: topnames
    description: ...
    docker-cmd: ["R", "-e", "shiny::runApp()"]
    docker-image: cpsievert/apps:shiny-topnames
  - name: worldBank-ggvis
    display-name: worldBank-ggvis
    description: ...
    docker-cmd: ["R", "-e", "shiny::runApp()"]
    docker-image: cpsievert/apps:shiny-worldBank-ggvis
  - name: zikar
    display-name: zikar
    description: ...
    docker-cmd: ["R", "-e", "shiny::runApp()"]
    docker-image: cpsievert/apps:shiny-zikar

logging:
  file:
    shinyproxy.log
